### ISSUE TITLE
Latent space advice

### ISSUE THREAD

**Issue by antmillar** [davidstutz/pointnet-auto-encoder#1]
Hi David, thanks for the repo and article you wrote they're very helpful

I've been trying to build an AE with modelnet + pointnet however my latent space always just converges to some mean 3d shape without much variation

I wondered if you had any tips to improve the result?

Thanks

Anthony

**Comment by davidstutz** [comment]
Sorry for the late reply.

I had similar problems with PointNets, as well, but I do not have a good out-of-the-box solution. I recommend simplifying your problem/shapes. Some sanity checks are: overfitting few (or even one) similar shapes or overfittingt wo very different shapes (where the mean does not make sense). If that works but it does not scale to more shapes, you model might not be expressive enough or the latent space might be too small. Also make sure to monitor the latent space mean/std during training to see at which point the latent space collapses (i.e., zero std).
