### ISSUE TITLE
Info about the auto-encoder

### ISSUE THREAD

**Issue by marcellobullo** [davidstutz/pointnet-auto-encoder#2]
Hi! 
The auto-encoder must be trained on a specific class (i.e. chairs) which implies that, once trained, it encodes/decodes point-clouds with specific shapes? Or it can extract features from different classes at the same time (i.e chairs, tables, desks,..)? Hope it's clear, thanks!

**Comment by davidstutz** [comment]
Sorry for the late reply. This depends on your application. Generally it will only provide meaningful features on the classes it was trained on.
